/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
/home/CEFCA/aaorsi/work/jpas_mock/src/readmock_chunk.py:84: RuntimeWarning: divide by zero encountered in log10
  Nlyc_ = np.log10(1.35) + np.log10(GalArr['sfr'][gsel]) + 53.0
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-17:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
Process Process-20:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./get_all_lines.py", line 108, in read_lightcone_chunk
    qpar = qZrelation(GalArr['Zcold'])  # assuming default pars.
ValueError: field named Zcold not found
